### ISSUE TITLE
Docs out of date

### ISSUE THREAD

**Issue by mcauser** [adafruit/micropython-adafruit-tsl2561#2]
I noticed a typo on:
http://micropython-tsl2561.readthedocs.io/en/latest/examples.html

Went to fix it and discovered it's already fixed.
https://github.com/adafruit/micropython-adafruit-tsl2561/commit/18fc50e2fa2e6a443f20aa752ef66aaebef8b657

Went back to the docs and found the Edit on GitHub link points to the original repo:
https://github.com/deshipu/adafruit-upy_tsl2561/blob/master/docs/examples.rst

Seems you need to reconfigure RTD to point to the new repo, so commits are deployed.
http://micropython-tsl2561.readthedocs.io

**Comment by deshipu** [comment]
Ah, thank you!

**Comment by deshipu** [comment]
Fixed now.
