### ISSUE TITLE
spurious interrupt on lux threshold less than 1

### ISSUE THREAD

**Issue by carterw** [adafruit/micropython-adafruit-tsl2561#3]
I'm trying to cause an interrupt to be generated (interrupt pin pulled low) when light level exceeds a high threshold but not on a low threshold in a situation where the device is sometimes in almost complete darkness. In principle this should be easy enough to do.

`TSL2561.threshold(cycles=2, min_value=0, max_value=100)`

What I'm seeing is that if the reported light level drops below 1 (very dark) an unwanted interrupt will occur. If, however, I set the min_value to 1 I do not get an interrupt on lux levels that are 1 or more. Only on levels below 1. This tells me that low thresholds of 1 and above work properly. The same problem occurs when I set min_value to None, which appears to cause the driver to write nothing to the low threshold register.

**Comment by carterw** [comment]
Experimenting further, I am seeing that the device never reports a light level below 0.5 even if you have your finger covering the surface. I tried bumping the gain up from the default 1x to 16x, then it reports 0.555... for the lowest light level and sometimes does not generate an interrupt.

Edit - putting an opaque object on the surface results in a reading of 0.5 regardless of the gain, and an interrupt is always generated.

**Comment by kattni** [comment]
Thank you for the detailed issue. We're not sure what's going on here! 

This library is no longer supported and is being deprecated., Please consider checking out the CircuitPython library https://github.com/adafruit/Adafruit_CircuitPython_TSL2561 for using the TSL2561 with microcontrollers.
